#!/bin/bash
#!/usr/bin/env bash
# encoding: utf-8
# Author: lyndon


_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

# Start Xvfb
Xvfb -screen 0 $XVFB_WHD -ac &
DISPLAY=:0 ratpoison &

chromium --no-sandbox $@ &
chromium=$!

wait $chromium
wait $xvfb